dist: bionic

language: ruby

services: docker

rvm:
  - 2.6.3

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - secure: ip6gXO+XNsgNpagW6ajZ19h77DF1F21Z3iE4JiiO6mQ25fhGiL/0Joh+JhH3/8w2sk8NUq1+KAu0Dz8gJ/gKhENb4aSXLyNKoLtQ1qWRX4IbpW+atS13PLzn5zZGYRCtFpuch1gMT7sQvdGEo9W7k2fu6ad/xkFv+QWn/VXmGmtQxfEQ2u+5Ckaa9nvtSDdzoPFRFbnFjylK1B2Sao3HV6Y5iVYfSAw3hqFjF9X4KfKPv3Cd3+8icNHMIDZWMhh7F6x9AjqahAAbxmvr7e4mZVjmSH5Q8ESwG7V3vJKr6i0y1OresINk3Fw4FcArVVuLbWajqLftMa4cWZygPIWo2vKLqSDqIT45+qP3nMUS05cg84sGS7dW0elPycWe4JZccrMF9c/n4n13YIoq1Ihh2fN4GhILRYsUc2K9M7UnAqbK80B+xrpx+yWPWKO5vUpP+s4zuSg7G4bZOVSQShQy1Q4UBSVnn/VZZ+46gRk8IJwzmvE4FJZ6B3rVbOrWPIjFcVBiDAmwUVCj4PXgs/BhGruwX9r9qWNADbQ+Y3IMn8nwoIG5b7YE4cHtTJK1VDhRY/8MP6bqX7acIgR4h20MeDnDnwE0vHNWlphuNw91HaHwYnm4qsYsab+w6YuhCtSFVPwGCC6kcePGKR3prgpu+RKaPgvxcJe7utXQggPJR70=

exclude: [vendor]

cache: bundler

before_install:
  - gem update --system
  - docker pull jekyll/jekyll:4.0
  - docker pull mirisbowring/texlive_ctan_full:2019
  - chmod +x ./script/texbuild.sh
  - chmod +x ./script/cibuild.sh

install:
  - gem install html-proofer
  - sudo apt-get update

script:
  - docker run --rm -it
      --volume="$PWD:/data"
      mirisbowring/texlive_ctan_full:2019
      ./script/texbuild.sh
  - find ./_posts-tex -name "*.tex" -type f -exec make4ht -l -um publish {} "svg" \;
  - docker run --rm -it
      --volume="$PWD:/srv/jekyll"
      jekyll/jekyll:4.0
      ./script/cibuild.sh
  - htmlproofer ./_site --disable-external

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
