dist: bionic

language: c

services: docker

env:
  global:
    secure: "qfLKGnXkOMlJcDVuYouluSlJKYVRz5hLlkHhKAw6V38Slmr7hUhWkH17yGLBaaXYnqXTHkQMXTM7xNNDIEaObh4ItH1CAiAFWG1Aw19n+7HuatiGWxCpGlOgv3UbnJezXJIz1kNxr+d0ebHw60eUynztRxYWxxeAqMVCdpchvTnyheOQW8zOEithz6I45eQ2AuWW9iEzXuHUmDrRi0vxvtbdw8RIdG/Pb6WHh7Ki436xrUis9secenBNDRZY47n3+/CjWMpD+eeE/VJP6b27aufFTmQh2YOIrO8teaSZeEeOke/BZK+aHvUrhygvXRZN4T74j3wCjP1IE/88vGwef1tNyo+r6vOIbGnAdQ37MFWOoX8nRVDJ15LbiFePB+UbiJSdEXyRVGEm2iuYjc2p/RsfA9NWZUIPAo32gREBP7TI6Zqk4NPUv3bemvTmi7/VxnxIZAX3lfeAtrJQovzTnejxrwumoeU3AMUIfADlGd2xsnk6e4fwvWEWtjQENUyCLtbeH/UR90JeQbM25vzoxFg/mJGzn5efEBvjMD+SgiNyrkR/uiKVmWokt4Bhsec+b7wuPp+zLH9zLr7GGSBmcDlWqAlWVsIwTlKLDdjw7cKZDZj4X7JAtDRTNQFrakll7/1DUcMxDALIYgg1L6YTBDzJJwghd2lWxcHoU6eb158="

before_install:
  - docker pull mirisbowring/texlive_ctan_basic:2019
  - chmod +x ./script/texbuild.sh

script:
  - mkdir tempfiles
  - find . -maxdepth 1 -name "*.html" -type f -exec mv {} tempfiles \;
  - find . -maxdepth 1 -name "*.css" -type f -exec mv {} tempfiles \;
  - docker run --rm -it
      --volume="$PWD:/data"
      mirisbowring/texlive_ctan_basic:2019
      ./script/texbuild.sh
  - rm -f *.aux *.xref *.tmp *.4tc *.4ct *.idv *.lg *.dvi *.logs *.html *.css
  - rm -v .make4ht
  - rm -rf script _posts-tex script
  - find tempfiles -maxdepth 1 -type f -exec mv {} . \;
  - rm -rf tempfiles
  - rm -v .travis.yml

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  repo: brandonhewer/brandonhewer.github.io
  target_branch: master
  keep_history: true
  on:
    branch: master
