dist: bionic

language: c

services: docker

env:
  global:
    - secure: "LY75n7MeEglaLdxXCwSdCjUMDDYjtX2/77Dn3l0mZt7s7E46Ige+I+5zg6dhqKCb3shPwmh/L7IuSGiid3k+lj7wPJ5+ZqtgPYuGc3WqDwBfoTBwAXk/26gTS5NIg2o67vrL2h8JtNCjfKeBr/myCfbElBJZiOCYnYedB5COWgcKD3VZVW1va45fOPbdv1NsDwRKu+dlmh2Z09HAnynIG3UX4S8ZB9PQ3mhzarfVP2Zt+b2rA/distxeloDSTjXXCvTj10FXSLBniuk/OaiGRt+VZpzafQ6aWjYz/xgzSinzL4jub0KO5d7RCmje/s7SPPlTH41SGUMpY+Z6JWURFCMjpwPvRvTXL7fDrAFuci4844oN5ITqreHW2M0IM17ncxmr1ABdQLtUzy1NHtUYE40fHYWkqMrLKG09Vtf65ZCkHV8fxBnleBXHnF/qiUNragdB0VRfY1oVWKfmVxOX2TPrwPcU8ZsBGfy/J2+/UjrnG/ZE28bX8nG1FWqbPXogL4BkxnyMnKsiLlQPbi32KAOoRIDcxYM6wn0CsR+qOPrUiaNYV2o/MxU1mrk6xtivttWxM7FHMWocb4WnprpBwDRdHSBBZiORw1/gNnC/tS5JHj19JowgLKlz7civkZ8h0kzOirI2Vc5BGK3V1Ljw0Mbd4d0nBaCP2T2HdqVP+/Y="

before_install:
  - docker pull mirisbowring/texlive_ctan_basic:2019
  - chmod +x ./script/texbuild.sh

script:
  - mkdir tempfiles
  - find . -name "*.html" -maxdepth 1 -type f -exec mv {} tempfiles \;
  - find . -name "*.css" -maxdepth 1 -type f -exec mv {} tempfiles \;
  - docker run --rm -it
      --volume="$PWD:/data"
      mirisbowring/texlive_ctan_basic:2019
      ./script/texbuild.sh
  - rm -f *.aux *.xref *.tmp *.4tc *.4ct *.idv *.lg *.dvi *.logs *.html *.css
  - rm -v .make4ht
  - rm -rf script
  - rm -rf _posts-tex
  - rm -rf script
  - mv tempfiles/* .
  - rm -rf tempfiles
  - rm -v .travis.yml

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  repo: brandonhewer/brandonhewer.github.io
  target_branch: master
  keep_history: true
  on:
    branch: master
