dist: bionic

language: c

services: docker

env:
  global:
    secure: "QbL6aCjp3Om+u+CdFM/6q84an2jFDlYegLMQovRXlav4cAAYYjxOU/ffd64x9OUkQZkwAQP9FXNP7WRN+fT0JZCwGPtOdiPfKUp0gWQpP11/IcJ4TMugTUwJuHrTCzZUbUDVkaK6bc2impKbmfAzbRSUAecLbt0l4ErFebyWAS7D2eIBfhrzOEiVwoJvT0WIxLgDFb/WI/3hNLnIqJIQoEniYLMo5+PaXXVig0olroZgEvVRp1UV+eBS7zryWkdxxFD09Le5b76rwfrKR6L5WxLMVvQbnbdikjQq3Xc2rtUhRxUhTnUGnMx/qzBdoNJ/AWJir60t/PtgiO4vNTIm2iyJlU/HTYVV+/cVvjTmXckO6ZDd738FbgknKW8x3/31OLMUlUoTC47AowrqthRpbmwAqKl3OJATPrjCf176qdpN+jrF3958a2B9Zws/QH5F4x9OuYMqMypFC3Fp+McEBUf4+e9qC8slOmnvbKHN2bIGaYiHQseKwcvQmFEB4UhefAQFSK147YZfzFq+TozQnC3y4eExYVKD++P7EP+qnNib38cdVzTYNFapcoz561nQWLtieU1phclO99bel5zfYoW/O0lYxNoEpfOGiHNI/OTCHpHQZo0A/eTkcC/WID5/r8fAijkELAAHElgvrQj1LjXrI5wcI6WbHRfpu2DcV7o="

before_install:
  - docker pull mirisbowring/texlive_ctan_basic:2019
  - chmod +x ./script/texbuild.sh

script:
  - mkdir tempfiles
  - find . -maxdepth 1 -name "*.html" -type f -exec mv {} tempfiles \;
  - find . -maxdepth 1 -name "*.css" -type f -exec mv {} tempfiles \;
  - docker run --rm -it
      --volume="$PWD:/data"
      mirisbowring/texlive_ctan_basic:2019
      ./script/texbuild.sh
  - rm -f *.aux *.xref *.tmp *.4tc *.4ct *.idv *.lg *.dvi *.logs *.html *.css
  - rm -v .make4ht
  - rm -rf script _posts-tex script
  - find tempfiles -maxdepth 1 -type f -exec mv {} . \;
  - rm -rf tempfiles
  - rm -v .travis.yml

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  repo: brandonhewer/brandonhewer.github.io
  target_branch: master
  keep_history: true
  on:
    branch: master
