dist: bionic

language: c

services: docker

before_install:
  - docker pull mirisbowring/texlive_ctan_basic:2019
  - chmod +x ./script/texbuild.sh

script:
  - mkdir tempfiles
  - find . -maxdepth 1 -name "*.html" -type f -exec mv {} tempfiles \;
  - find . -maxdepth 1 -name "*.css" -type f -exec mv {} tempfiles \;
  - docker run --rm -it --volume="$PWD:/data" mirisbowring/texlive_ctan_basic:2019 ./script/texbuild.sh
  - rm -f *.aux *.xref *.tmp *.4tc *.4ct *.idv *.lg *.dvi *.logs *.html *.css
  - rm -v .make4ht
  - rm -rf script _posts-tex script
  - find tempfiles -maxdepth 1 -type f -exec mv {} . \;
  - rm -rf tempfiles
  - rm -v .travis.yml

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  repo: brandonhewer/brandonhewer.github.io
  target_branch: master
  keep_history: true
  on:
    branch: master

env:
  global:
    secure: 3uiSIM63z3hfm0Y8sssjoMxcAQXga6qlboiQVJwPEWzb/2HWY/RIzfLdsrmrbs+4gubJ6fYkn0h1kQhRgwbzrmTwlCNh//2EqfdA3tiP1CGceyzQgAnaw0R7tNl1RTxZ+hgm0BRbGiz68ThAZRfDSjAlDwcYlqvjwhMFklo/rpkS400vkpT3zoce8+eeoLNN/9uD1FtFuA8SINpmHr8YBtmp3laU9JzpHe9q8HCClCgPg/kOwpRe6+0Hc0WY6AGVUj851hHTqlQrcqeuL6AsDfuznZccTGLknsLnT7zCqNb8rZj4EKrAH2J4xFLW4CWDLsIPzK275M8P0KI7cdF/rqqaWlwq46KFn2ec6Nkmk1ERGp+Fu0hnxQtYaA7RuqIIU2xneqLd0OkjiO7c0EDBT1mAsZEkwgpYy0JVcGTKF1vXgfSHzbzIgU+MItRENbz3irKcAY9G6wEKJXsNAYYxQuDPms9H/pshS8LQn6Of2u9Aq+AOD6mqX/SWQBV3l4ufmfJBiGtwpA9o2ZgfQ8BQu9nkcEQSiUm8E5rEOK4ZEU6TlWGPyAFBAXT3lo1aquNXmgUodOocWJ/p9jTNG/d93plW0kujmb9WOJptIqRNZ1EdK+zr7yuoHvcG0zrtiWjmGxFfJ0+oCepx1lX+RzQkFR/xvy8bnj1+NxYoWC2xbWc=
